"""add_ai_profile_to_child

Revision ID: df54139dc760
Revises: 20260529_0001
Create Date: 2026-05-30 15:10:47.820669+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'df54139dc760'
down_revision: Union[str, None] = '20260529_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children_profiles', sa.Column('ai_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_consultation_records_booking_id'), 'consultation_records', ['booking_id'], unique=False)
    op.create_index(op.f('ix_consultation_records_family_id'), 'consultation_records', ['family_id'], unique=False)
    op.add_column('course_modules', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('courses', 'video_file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('video_file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('course_modules', 'updated_at')
    op.drop_index(op.f('ix_consultation_records_family_id'), table_name='consultation_records')
    op.drop_index(op.f('ix_consultation_records_booking_id'), table_name='consultation_records')
    op.drop_column('children_profiles', 'ai_profile')
    # ### end Alembic commands ###
